name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: debian-latest

    steps:
      - name: Checkout code
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout ${{ github.ref }}

      - name: Setup Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          node -v
          npm -v

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        run: |
          git clone --branch=docs https://github.com/${{ github.repository }}.git out
          rsync -av --delete ./dist/ out/demo/
          cd out
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin docs
